name: DAST Scan (ZAP)

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for App
        run: sleep 40

      -- name: Run ZAP Scan
  run: |
    mkdir -p zap-reports

    docker run --rm \
      -v $PWD/zap-reports:/zap/wrk \
      ghcr.io/zaproxy/zaproxy:stable \
      zap-baseline.py \
      -t http://${{ secrets.EC2_HOST }} \
      -r /zap/wrk/dast-report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: dast-report.html
