name: DAST - OWASP ZAP Scan

on:
  push:
    branches: ["main"]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable \
          zap-baseline.py -t http://51.20.4.44 -r dast-report.html

      - name: Upload DAST Report (BOX)
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: dast-report.html
