name: DAST Security Scan (OWASP ZAP)

on:
  workflow_run:
    workflows: ["Build Push Deploy Pipeline"]
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for app to be ready
        run: sleep 40

      - name: Run OWASP ZAP Scan
        run: |
          docker run -t owasp/zap2docker-weekly zap-baseline.py \
          -t http://${{ secrets.EC2_HOST }} -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
