name: DevSecOps Pipeline (SAST + DAST)

on:
  push:
    branches: [ "main" ]

jobs:

# =========================
# 🟢 SAST - SonarQube
# =========================
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=juice-shop \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

# =========================
# 🔵 DAST - OWASP ZAP FIXED
# =========================
  dast:
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZAP workspace folder
        run: mkdir -p zap-wrk

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zap-wrk:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy zap-baseline.py \
            -t http://51.20.4.44:3000 \
            -r zap-report.html
